import { Metadata } from "next";
import { FC, PropsWithChildren, ReactElement } from "react";

export const metadata: Metadata = {
  title: "Car info",
  description: "Generated by create next app",
};

const CarLayout: FC<PropsWithChildren<unknown>> = ({ children }) => {
  return (
    <div className='flex min-h-screen flex-col items-top p-8'>{children}</div>
  );
};

export default CarLayout;
