import "./globals.css";
import { Inter } from "next/font/google";
import { FC, PropsWithChildren } from "react";
import Header from "@/components/header/Header";
import { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: FC<PropsWithChildren<unknown>> = ({ children }) => {
  return (
    <html lang='en' className={inter.className}>
      <body>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
};

export default RootLayout;
